Clone attributes
Icinga/ipl-html pull request #110
Opened 2023-02-15 12:04 UTC by lippserd

Right now we have an attribute cloning use case where we [duplicate the primary submit button](https://github.com/Icinga/ipl-web/pull/104) and add it as the first element to ensure that it is used for implicit form submission. The submit button to be cloned can have attributes and callbacks that must also be present on the clone, such as `formaction`, `formmethod` and `formnovalidate`, so simply not using the original attributes is not an option.

Until [proper cloning](https://github.com/Icinga/ipl-html/pull/96) is implemented, it is imperative to re-register attribute callbacks for attributes where a callback exists and the clone provides a changed value.

2023-02-15 12:04 UTC, lippserd commented
See Icinga/ipl-web#104 for the duplicate submit button PR and #96 for proper cloning.

2023-02-15 15:26 UTC, nilmerg requested changes
Please integrate the tests from #96 here.

2023-02-17 07:30 UTC, lippserd commented
> Please integrate the tests from #96 here.

Added my own test. The PR referenced contains two tests that basically do the same thing, but only change one attribute. Here we also test adding and removing attributes and cloning already cloned attributes.

2023-02-17 08:28 UTC, nilmerg approved these changes

2023-02-17 08:28 UTC, merged