GIthub Actions: Add PhpStan
Icinga/ipl-html pull request #123
Opened 2023-06-19 11:41 UTC by sukhwinder33445

2023-08-23 10:17 UTC, nilmerg requested changes

2023-08-23 10:17 UTC, nilmerg commented on src/HtmlDocument.php
> -        return $this;
why is this removed and not added in the overrides?

2023-08-23 10:17 UTC, nilmerg commented on src/FormDecorator/DdDtDecorator.php
> +                $classes->isEmpty()
There should rather `getValue` being called above. Otherwise `$classes` can never be a string or an array.

2023-08-23 10:17 UTC, nilmerg commented on src/Attribute.php
> +    public function __toString()
Why is this needed? i.e. Where are attributes casted to string?

2023-08-23 10:17 UTC, nilmerg commented on phpstan.neon
> +        - '#Parameter \#2 \$value of static method .#' # Attributes -> Line 43
Are all of these unfixable or did you just ignore them due to time constraints? If it's the latter, this should be in the baseline configuration.

2023-08-23 10:17 UTC, nilmerg commented
and please rebase

2023-08-23 11:37 UTC, yhabteab commented on phpstan.neon
> +        - '#Parameter \#2 \$value of static method .#' # Attributes -> Line 43
done

2023-08-24 07:07 UTC, nilmerg requested changes

2023-08-24 07:07 UTC, nilmerg commented on src/FormElement/FileElement.php
> +                    Html::tag(
Mhm, we should use `HtmlElement` here as well. Introducing and using `Html` here just for this icon feels wrong.

2023-08-24 09:46 UTC, nilmerg commented on src/FormElement/FileElement.php
Please amend Ravi's commit

2023-08-24 12:16 UTC, nilmerg approved these changes

2023-08-24 12:16 UTC, merged