PHPDoc and small fixes/enhancements for the Attribute and Attributes classes
Icinga/ipl-html pull request #4
Opened 2018-08-06 13:58 UTC by lippserd

Most of this PR introduces PHPDoc and some method reordering. Notable fixes are:

* Removed `setName()`. Runtime changes must be forbidden for name. I considered to make this protected but then it is also subject to runtime changes in subclasses.
* `Attribute::render()` renders empty and boolean false attrs as the empty string
* `Attribute::escapeValue()` now expects a glue string
* New method `Attribute::removeValue()`

2018-08-06 15:25 UTC, Thomas-Gelf requested changes

2018-08-06 15:25 UTC, Thomas-Gelf commented on src/Attribute.php
> +    public function removeValue($value = null)
Please make $value required, IMO who wants to set an attribute to `null` without removing the Attribute should be forced to run `setValue(null)`.

2018-08-06 15:25 UTC, Thomas-Gelf commented on src/Attribute.php
> +        if (! is_array($this->value)) {
Please relax this. It is perfectly legal to have an `Attribute` with a string value and adding another value later on. You do not have to care whether it is already an array or not, same should apply when removing values. If the current value is a string and the string matches the given value it should be nulled, if it is a string which doesn't match it should do nothing and return without an error.

2018-08-06 15:25 UTC, Thomas-Gelf commented on src/Attributes.php
>      /**
Just a generic note -> please do not push commits which change and move code in one commit - it's extremely annoying to read them, and you have to be very, very careful to not overlook changes.

2018-08-06 15:25 UTC, Thomas-Gelf commented on src/Attributes.php
> +        if ($attribute instanceof static) {
`Attributes` is correct here, `static` is wrong. Reasoning: when extending this class you still want "normal" `Attributes` to be accepted, wouldn't you? Same goes true for `get`, there it has already been wrong. You can correct that one too if you want.

2018-08-06 15:25 UTC, Thomas-Gelf commented on src/Attribute.php
> -        // TODO: escape
Please leave the TODO in place unless resolved.

2018-08-06 15:25 UTC, Thomas-Gelf commented on src/Attribute.php
> -        // TODO: escape differently
One more unresolved TODO, should remain in place.

2018-08-06 15:25 UTC, Thomas-Gelf commented on src/Attribute.php
> +    public static function escapeValue($value, $glue)
Can we leave `$glue = ' '` as the default here?

2018-08-06 15:25 UTC, Thomas-Gelf commented on src/Attribute.php
> -    /**
Could you please keep `setName()` and make it protected? I hate constructors with too much logic, it's always a mess when you want to extend/override them.

2018-08-06 15:25 UTC, Thomas-Gelf commented on src/Attribute.php
> +                return $this->renderName();
Given these options:

```html
<input required />
<input required="required" />
<input required="" />
```
Do you have any preference?

2018-08-06 15:26 UTC, Thomas-Gelf commented
Thanks for this, I added some comments

2018-08-06 18:15 UTC, lippserd commented on src/Attribute.php
> -    /**
👍 I considered this but decided to just remove it so it's not that easy to change the name in subclasses. But since it's possible to override the constructor anyways, I'll make it protected.

2018-08-06 18:17 UTC, lippserd commented on src/Attribute.php
> +                return $this->renderName();
The first one.  We render HTML5.

2018-08-06 18:18 UTC, lippserd commented on src/Attribute.php
> +    public static function escapeValue($value, $glue)
Sure!

2018-08-06 18:18 UTC, lippserd commented on src/Attribute.php
> -        // TODO: escape differently
What should be escaped differently here?

2018-08-06 18:19 UTC, lippserd commented on src/Attribute.php
> -        // TODO: escape
There is no escape for attribute names. Either it is valid or invalid.

2018-08-06 18:21 UTC, lippserd commented on src/Attributes.php
>      /**
Absolutely. I'll split the commits in question.

2018-08-06 18:51 UTC, Thomas-Gelf commented on src/Attribute.php
> +                return $this->renderName();
That's what I would also have said. However:

2018-08-06 18:52 UTC, Thomas-Gelf commented on src/Attribute.php
> +                return $this->renderName();
[3.2.2 Boolean attributes](https://www.w3.org/TR/2008/WD-html5-20080610/semantics.html):
> If the attribute is present, its value must either be the empty string or a value that is a case-insensitive match for the attribute's canonical name, with no leading or trailing whitespace.

2018-08-06 18:59 UTC, Thomas-Gelf commented on src/Attribute.php
> -        // TODO: escape differently
The attribute value should not be escaped like any HTML text node, as [attributes](https://www.w3.org/TR/html5/syntax.html#elements-attributes) have different semantics. This implementation should be safe, but it is not correct.

2018-08-06 19:01 UTC, Thomas-Gelf commented on src/Attribute.php
> -        // TODO: escape differently
Googled a nice [example](https://mathiasbynens.be/notes/html5-id-class):

```html
<p id="#">Foo.
<p id="##">Bar.
<p id="♥">Baz.
<p id="©">Inga.
<p id="{}">Lorem.
<p id="“‘’”">Ipsum.
<p id="⌘⌥">Dolor.
<p id="{}">Sit.
<p id="[attr=value]">Amet.
<p id="++++++++++[>+++++++>++++++++++>+++>+<<<<-]>++.>+.+++++++..+++.>++.<<+++++++++++++++.>.+++.------.--------.>+.>.">Hello world!
```

I want to be able to use those.

2018-08-06 19:02 UTC, lippserd commented on src/Attribute.php
> +                return $this->renderName();
You are looking at a working draft 😆 

Please see here: https://www.w3.org/TR/html5/infrastructure.html#sec-boolean-attributes

2018-08-06 19:03 UTC, Thomas-Gelf commented on src/Attribute.php
> -        // TODO: escape
You're right, we should drop the method and replace it with `assertValidName` eventually throwing an `InvalidArgumentException`.

2018-08-06 19:03 UTC, Thomas-Gelf commented on src/Attributes.php
>      /**
Don't worry, it's not worth the effort. Next time!

2018-08-06 19:07 UTC, Thomas-Gelf commented on src/Attribute.php
> +                return $this->renderName();
Thanks Google. I knew my code must have been correct :laughing:

Btw:

>  A boolean attribute without a value assigned to it (e.g. checked) is implicitly equivalent to one that has the empty string assigned to it (i.e. checked="").

I was also wondering because Firefox Developer tools continue to show `<input required="" />` while our code says `<input required />`. The one we opted for looks better to me, let's keep it.

2018-08-07 07:17 UTC, lippserd commented
Made all the changes you've requested. I'd like to postpone the name validation in order to get this merged.

2018-08-07 07:23 UTC, Thomas-Gelf approved these changes

2018-08-07 07:23 UTC, merged