Support mustache template mapping
Icinga/ipl-html pull request #41
Opened 2021-04-23 07:50 UTC by raviks789

Earlier FormattedString class did not support mustache template mapping. Here mustache template mapping
for Html tags has been introduced.

fixes #33

2021-04-27 05:50 UTC, Thomas-Gelf requested changes
Please note that the solely purpose of the `FormattedString` class is to support `formatted strings` as known from the C language. While personally not feeling the immediate need for such a solution, I have no objections against introducing support for a templating language. However, I'd suggest moving it to a dedicated class, IHMO `FormattedString` is the wrong place for this.

2021-04-29 07:16 UTC, Thomas-Gelf approved these changes

2021-04-30 08:04 UTC, lippserd commented
I agree that this should be something like `TemplatedString`.

2021-04-30 13:17 UTC, nilmerg requested changes
We had the discussion about the possible interfaces:

* `...('{{#total}}Total{{/total}} %d', ['total' => Html::tag('span')], 42)`
* `...('{{#total}}Total{{/total}} %d', total: Html::tag('span'), 42)` (PHP8+)
* `...('{{#total}}Total{{/total}} %d', 42)->setMustacheTemplates(['total' => Html::tag('span')])`

The latter is what we agreed upon eventually. The second one would be the cleanest, but it's no option. The first however, although I said it's not the best, is still the best compromise I think. (Now, when thinking about it again)

It should be possible to support this:

`$title = TemplateString::create('{{#total}}Total{{/total}} %d {{#num}}#{{/num}}', ['total' => Html::tag('span'), 'num' => Html::tag('i')], 42);`

The position of the template arguments though is **not** important. Because I think of the processing this way:

1) Filter the arguments by type (scalar values are parameters for `vsprintf`, arrays for the template)
2) `vsprintf` arguments are still registered in their respective order so that when passing them the result is this: `'{{#total}}Total{{/total}} 42 {{#num}}#{{/num}}'`
3) arrays are merged together so that at the end a single map exists to fill the template with: `'<span>Total</span> 42 <i>#</i>'`

So please change the implementation so that it works this way.
Also, please do the following:

* Rename the class to `TemplateString` (@lippserd *Templated* isn't a word :teacher: )
* Let the class inherit from `FormattedString`, and let it perform the `vsprintf` handling
  * For this to work, you'll need to filter the arguments by type in the constructor
* The template processing should happen deferred, not instantly
  * Perform it as part of method `render()` instead

I'll provide you next week with additional test cases of the various usages I imagine for this.

2021-05-07 07:34 UTC, nilmerg commented
I pushed some additional test cases now. Though, to a different branch to not disrupt your workflow. Once pulled, you can cherry pick it instead: `git cherry-pick 977fbff`

2021-05-21 07:45 UTC, nilmerg requested changes
Left some comments in the constructor and the `render` method. Regarding the actual parsing, we should talk directly. It's too difficult to give my thoughts based on text :sweat_smile:

2021-05-21 07:45 UTC, nilmerg commented on src/TemplateString.php
> +        $this->templateArgs = [];
You could already initialize this with an empty array. (In the property definition)

2021-05-21 07:45 UTC, nilmerg commented on src/TemplateString.php
> +            if (is_array($val) && $this->isAssoc($val)) {
I believe you can replace `$this->isAssoc($val)` with `is_string(key($val))`. If the first key isn't a string the array isn't a template argument. If there are indeed other keys which are not strings, the rendering should fail in my opinion. String keys don't matter for `FormattedString` anyway, so a developer shouldn't mix key types in any case. And if it's done, it should throw an error instead of silently accepting it.

2021-05-21 07:45 UTC, nilmerg commented on src/TemplateString.php
> +                $this->templateArgs[$key] = $val;
If you'd use `$this->templateArgs += $val` you can remove the array_merge below. The `+` operator with arrays doesn't override existing keys though, but I don't think that's an issue. If we wouldn't have to support PHP 7+ ( :rofl: ) we could use PHP 8's named args, then arg names would be unique anyway.

2021-05-21 07:45 UTC, nilmerg commented on src/TemplateString.php
> +        $args = array_values($args);
Please already populate an array during the loop. It's more efficient that way.

2021-05-21 07:45 UTC, nilmerg commented on src/TemplateString.php
> +        return $formattedstring;
That could be a single line :wink:

2021-05-25 13:05 UTC, nilmerg commented on src/TemplateString.php
> +            $char = $this->readChar();
You could combine that like so:

```suggestion
        while (($char = $this->readChar()) !== false) {
```

2021-05-25 13:07 UTC, nilmerg commented on src/TemplateString.php
> +            }
You could move that to the top (`if ($char !== '{') {` and combine it with a `continue`. This way you can remove one level of indentation and what happens for non-template chars is instantly obvious.

2021-05-25 13:08 UTC, nilmerg commented on src/TemplateString.php
> +        return (new HtmlDocument())->add($buffer);
Please combine both lines, and put an empty line before them. There's a control structure beforehand after all.

2021-05-25 13:10 UTC, nilmerg commented on src/TemplateString.php
> +                $this->pos++;
What if there's not a `{` after? Please check for that as well.

2021-05-25 13:11 UTC, nilmerg commented on src/TemplateString.php
> +                $end = $this->readChar() === '/';
I'm sure that's solvable with a single call to `readChar` ;)

2021-05-25 13:17 UTC, nilmerg commented on src/TemplateString.php
> +                    $buffer .= $this->readUntil();
Can't you just do this?: (`$templateHandle` is what I imagine being the result of the single call to `readChar` above :wink: )

```suggestion
                    $buffer = '{{' . $templateHandle . $templateKey;
```

2021-05-25 13:53 UTC, nilmerg commented on src/TemplateString.php
> +                    $buffer .= $char;
With this, you're essentially parsing the chars all over again. Please do it the same as I suggested for lines 72 to 74.

2021-05-25 13:56 UTC, nilmerg commented on src/TemplateString.php
> +                $next = $this->string[$this->pos--] === '}';
Please take a look here again. Why are you post-decrementing the position? Why are you incrementing it by `2` in various places below? There's too much forward and backward to me here. The increments by `2` below shouldn't be necessary as I see it.

2021-05-26 07:54 UTC, nilmerg requested changes

2021-05-26 07:54 UTC, nilmerg commented on src/TemplateString.php
> +            $next = $this->string[$this->pos] === '}';
Please use `readChar` here. You're interested in the next char and later on you're also incrementing the position. The method does both things already.

2021-05-26 07:54 UTC, nilmerg commented on src/TemplateString.php
> +            }
Please use that as the first `if`. Then you can remove the `&& $next` from all other branches. (I'd request to add that to the `$for === $templateKey` condition anyway.) The `if` should check directly for `$nextChar !== '{'` and use `$nextChar` to populate the buffer.

2021-05-26 07:54 UTC, nilmerg commented on src/TemplateString.php
> +            } elseif ($for === $templateKey) {
Please also check for `$end` here.

2021-05-26 07:54 UTC, nilmerg commented on src/TemplateString.php
> +        if ($this->pos === $this->length && !empty($this->unclosed)) {
The `$this->unclosed` array isn't necessary. There is never more than one entry in it. It's also never required outside the current scope. Use `$for !== null` here instead and reset `$for` above instead of popping the value from the array.

2021-05-26 07:54 UTC, nilmerg commented on src/TemplateString.php
> +                if (in_array($templateKey, array_keys($this->templateArgs), true)) {
Please.. use `isset($this->templateArgs[$templateKey])` :pray:

2021-05-26 07:54 UTC, nilmerg commented on src/TemplateString.php
> +                'Unbounded opening of template: %s',
Use `Unbound` here. `Unbounded` isn't quite the correct term for this.

2021-05-26 07:54 UTC, nilmerg commented on src/TemplateString.php
> +                    'Unbounded closing of template: %s',
`Unbound` as well, please.

2021-05-26 07:54 UTC, nilmerg commented on src/TemplateString.php
> +     * @param null $for
Please add a method description above. And an empty line before and after. And not `null` but `string` as type hint.

2021-05-26 07:54 UTC, nilmerg commented on src/TemplateString.php
> +    protected $length;
Please add doc blocks here.

2021-05-26 07:54 UTC, nilmerg commented on src/TemplateString.php
> + *     ]
That example doesn't quite show the advantage of this template functionality. Use this instead:

```suggestion
* $info = TemplateString::create(
*      'Follow the {{#doc}}HTML documentation{{/doc}} for more information on {{#strong}}HTML elements{{/strong}}',
*      [
*          'doc'    => new Link(null, 'doc/html'),
*          'strong' => Html::tag('strong')
*      ]
```

2021-05-26 10:34 UTC, nilmerg reviewed
I like what I see! :heart: 

Though, there's still a test failing.

2021-05-26 11:23 UTC, nilmerg approved these changes
It's like fine wine :wink: 

Thank you Ravi!

2021-05-26 11:27 UTC, merged