Introduce PasswordElement class
Icinga/ipl-html pull request #57
Opened 2021-11-22 09:23 UTC by yhabteab

2021-11-22 13:39 UTC, yhabteab commented
@cla-bot check

2021-11-29 14:59 UTC, nilmerg requested changes
Web 2's `ResourceConfigForm` doesn't include the stored password in the DOM. I think we should do the same but natively in the element itself. I believe this should work, since `ipl\Html\Form` can be (and in this case is) always being populated with the configuration:

* Don't use property `$value` of `ipl\Html\FormElement\Password` to render the `value` attribute, use a constant dummy password instead
  * Use an attribute callback for this
* Don't accept the dummy password as value for property `$value` (otherwise the real password is overridden and cannot be retrieved again by `getValue()`)

This should ensure that:

* A call to `setValue()` with the real password still stores it in property `$value` (Done by `FormElements::populate()`)
* A call to `getValue()` still returns the real password, if one got set by `setValue()` (Done by `FormElements::getValues()`)
* The form doesn't render the real password in the DOM, but shows that a password is set
* The form accepts a new password

2021-12-08 08:12 UTC, nilmerg requested changes
There's more, but I'd like to tackle that in person.

2021-12-08 08:12 UTC, nilmerg commented on src/Form.php
> +        $this->onValidate();
The only possible chance to reset `isValid` is to call `validate()` directly, which no-one does, to my knowledge. So why is this necessary?

2021-12-08 08:13 UTC, nilmerg commented on src/FormElement/FormElements.php
> +            $element->setValueCandidates($this->populatedValues[$name]);
What's the outcome here?

2021-12-08 09:11 UTC, yhabteab commented on src/Form.php
> +        $this->onValidate();
See [here](https://github.com/Icinga/icingadb-web/blob/master/application/forms/ApiTransportForm.php#L97).

2021-12-08 11:21 UTC, yhabteab commented on src/FormElement/FormElements.php
> +            $element->setValueCandidates($this->populatedValues[$name]);
Eric has decided to introduce a custom interface and this will then be implemented by `BaseFormElement`.

2021-12-08 14:57 UTC, nilmerg requested changes

2021-12-08 14:57 UTC, nilmerg commented on src/FormElement/PasswordElement.php
> +        $form->on(Form::ON_VALIDATE, function () use ($form) {
`$form` is passed as argument to the handler, use that instead.

2021-12-08 15:11 UTC, yhabteab commented on src/FormElement/PasswordElement.php
> +        $form->on(Form::ON_VALIDATE, function () use ($form) {
Do you mean this `Form::ON_VALIDATE` => `$form::ON_VALIDATE` or something else? I did not understand the request change correctly.

2021-12-08 15:29 UTC, nilmerg commented on src/FormElement/PasswordElement.php
> +        $form->on(Form::ON_VALIDATE, function () use ($form) {
`$form->on(Form::ON_VALIDATE, function () use ($form) {` vs `$form->on(Form::ON_VALIDATE, function ($form) {`

2021-12-09 07:40 UTC, nilmerg approved these changes

2021-12-09 07:43 UTC, merged