Don't always render error messages even with correct select options
Icinga/ipl-html pull request #60
Opened 2022-01-24 14:25 UTC by yhabteab

2022-01-25 09:46 UTC, nilmerg commented
I don't think this is the correct solution. This only occurs because upon a autosubmit, the form is partially validated. There's nothing wrong with this. Also if an element is asked to validate, it should do so no matter the form's state.

If I'm not mistaken, the element will be valid in case a wrong value is set with `setValue()` without submitting the form. This is bad.

Please think of an alternative. (But don't validate in `setValue()` e9ad70cd9d6bc9dd8fd956efa052fd2ae7006805)

2022-01-25 19:12 UTC, yhabteab commented
The problem is, we don't have the ability to find out, that a select element can be dependent on another select element. And when the parent element is autosubmitted, previous value of the child element are also submitted. Seeing as you don't like the first solution, I have introduced a new `SelectElement` attribute called `dependsOn` which allows us to cache the `parent` selectelement name and get this filtered out using jquery.

2022-01-31 09:13 UTC, nilmerg requested changes
This still has a rather big flaw: Consider a form with two auto-submitting elements, each with its own individual dependent element.

```
1st autosubmit
|_ dependent element

2nd autosubmit
|_ dependent element
```

Interacting with the second autosubmit causes the dependent element of the first one to be cleared.

This is due to the fact, that the dependency check doesn't involve the parent element at all. But I guess you asked yourself already that question: How should it?

I guess, not at all. Thinking about this, I only see one last option: Completely handing over the control to concrete forms by only providing the required tools.

A concrete form has all the knowledge. It knows when a default value has gone invalid and it knows which options are provided by a select element. By giving the concrete form now the ability to control which elements should be populated, it can solve the problem by itself.

```
if firstAutosubmitValue === 'optionA'
    firstOptions = ['a', 'b', 'c']
else
    firstOptions = ['d', 'e', 'f']
endif

if firstOptionPopulatedValue not in firstOptions
    form.clearPopulatedValue('firstOption')

form.addElement('firstAutosubmit', ...)
form.addElement('firstOption', ...)
```

`clearPopulatedValue()` should be a no-op in case the form has been submitted by the user. What's sent explicitly by the user must not be ignored.

2022-01-31 10:56 UTC, nilmerg requested changes

2022-01-31 10:56 UTC, nilmerg commented on src/Form.php
> +    public function clearPopulatedValue($name)
`$this->populatedValues` originates from `FormElements`, please add this there instead.

2022-01-31 10:56 UTC, nilmerg commented on src/FormElement/SelectElement.php
> +            $value && (
Please check for `!== null` here, the empty string and a zero may both be valid option ids.

2022-01-31 10:56 UTC, nilmerg commented on src/FormElement/SelectElement.php
>          } elseif ($this->isRequired() && strlen($value) === 0) {
`strlen($value) === 0` then has to change as well. If `$value` is NULL, it must not be passed to `strlen()`, but if the value is missing, it can actually only be NULL, so `$value === null` should be enough here.

2022-02-01 08:30 UTC, nilmerg commented on src/Form.php
> +    public function clearPopulatedValue($name)
Think of it this way: `$form->hasBeenSubmitted()` is part of a public interface, `FormElements::$populatedValues` however is not. It's perfectly fine that a class which uses this trait implements a method to solve it's requirements. But it's bad design that it accesses a property from a trait. It's technically possible, but should be avoided IMHO.

2022-02-01 09:20 UTC, nilmerg approved these changes

2022-02-09 14:24 UTC, merged