FormElement: Add MultiSelect element
Icinga/ipl-html pull request #65
Opened 2022-07-13 13:46 UTC by sukhwinder33445

2022-07-27 14:23 UTC, nilmerg requested changes

2022-07-27 14:23 UTC, nilmerg commented on src/FormElement/MultiSelectElement.php
> +     */
The compact version please.

2022-07-27 14:23 UTC, nilmerg commented on src/FormElement/MultiSelectElement.php
> +        $this->getAttributes()->add('multiple', true);
If you initialize `BaseHtmlElement::$defaultAttributes` you don't need to override the constructor. (Preferred)

2022-07-27 14:23 UTC, nilmerg commented on tests/FormElement/MultiSelectElementTest.php
> +            'label'   => 'Customer',
What's that? Seems useless to me. Please remove it from all tests.

2022-07-27 14:23 UTC, nilmerg commented on tests/FormElement/MultiSelectElementTest.php
> +        $select->setValue('Here');
Of course, a label can't be chosen, so this should test whether `sub` can be chosen or not.

2022-07-27 14:23 UTC, nilmerg commented on tests/FormElement/MultiSelectElementTest.php
> +    public function testOptionValidity()
Shouldn't this also test multiple selected options? There seems to be no other test for this at least.

2022-07-28 12:21 UTC, nilmerg requested changes

2022-07-28 12:21 UTC, nilmerg commented on src/FormElement/MultiSelectElement.php
> +        return in_array($optionValue, $this->getValue());
`in_array()` also supports loose and strict comparison, why not utilize it?

2022-07-28 12:21 UTC, nilmerg commented on src/FormElement/MultiSelectElement.php
> +        }
I think the element should have authority over what's valid in the first place. If it's a forbidden value, why validate it further? This may even pose a security risk depending on what's offered and how it's validated further.

2022-07-28 12:21 UTC, nilmerg commented on src/FormElement/SelectElement.php
> +    /** Whether the given option is a selected option
Doesn't this look ugly to you? To me it does.

2022-07-29 07:42 UTC, nilmerg requested changes

2022-07-29 07:42 UTC, nilmerg commented on src/FormElement/SelectElement.php
> +            $this->addMessage(sprintf($this->translate('%s is not allowed here'), $value));
The single quotes around the value are removed now. I'd prefer to keep them. As everywhere else where you've changed this.

2022-07-29 07:42 UTC, nilmerg commented on src/FormElement/SelectElement.php
> +        if ($this->isSelectedOption($value)) {
Please insert an empty line here.

2022-08-02 07:51 UTC, nilmerg submitted a review, later dismissed

2022-11-07 09:13 UTC, nilmerg submitted a review, later dismissed

2022-11-07 12:58 UTC, lippserd requested changes
Please use [nowdoc](https://www.php.net/manual/en/language.types.string.php#language.types.string.syntax.nowdoc) for expected HTML.

2022-11-07 12:58 UTC, lippserd commented on src/FormElement/MultiselectElement.php
> +    protected function registerValueCallback(Attributes $attributes)
Please do it like this:

```php
    public function getValueAttribute()
    {
        // select elements don't have a value attribute
        return null;
    }

2022-11-07 12:58 UTC, lippserd commented on src/FormElement/MultiselectElement.php
> +    protected $defaultAttributes = ['multiple' => true];
This is an essential attribute and should therefore be added during `assemble()`.

2022-11-07 12:58 UTC, lippserd commented on src/FormElement/MultiselectElement.php
> +        BaseFormElement::validate();
Why not `parent`?

2022-11-07 12:58 UTC, lippserd commented on src/FormElement/SelectElement.php
> +            $this->addMessage(sprintf($this->translate("'%s' is not allowed here"), $value));
Possible candidate for `InArrayValidator` or `DeferredInArrayValidator`.

2022-11-07 16:16 UTC, sukhwinder33445 commented on src/FormElement/MultiselectElement.php
> +        BaseFormElement::validate();
Because the parent class checks its own value first, since I already have a loop above for this check, I skip calling the parent method.

2022-11-07 16:17 UTC, sukhwinder33445 commented on src/FormElement/SelectElement.php
> +            $this->addMessage(sprintf($this->translate("'%s' is not allowed here"), $value));
I have already created a new [PR](https://github.com/Icinga/ipl-html/pull/83) for this.

2022-11-07 16:19 UTC, lippserd commented on src/FormElement/SelectElement.php
> +            $this->addMessage(sprintf($this->translate("'%s' is not allowed here"), $value));
But I don't see its usage here.

2022-11-07 16:33 UTC, lippserd requested changes

2022-11-07 16:33 UTC, lippserd commented on src/FormElement/MultiselectElement.php
> +        BaseFormElement::validate();
Exactly. In addition we have duplicated code. This shows that the code flow is flawed, and it raises the question of why we even have a separate element for this. Instead, specifying the multiple attribute for the select element should just work.

2022-11-08 11:09 UTC, sukhwinder33445 commented
Add `multiple` attribute functionality to [SelectElement](https://github.com/Icinga/ipl-html/pull/88).

2022-11-08 11:09 UTC, closed without merging