FormElement: Add `FileElement`
Icinga/ipl-html pull request #66
Opened 2022-07-15 13:57 UTC by sukhwinder33445

2022-09-30 09:14 UTC, sukhwinder33445 commented
@cla-bot check

2022-10-21 09:26 UTC, lippserd submitted a review, later dismissed
In addition to the changes requested, please test actual requests with `ServerRequestInterface:: withUploadedFiles()`.

2022-10-21 09:26 UTC, lippserd commented on src/FormElement/FileElement.php
> +        $this->value = $form->getRequest()->getUploadedFiles();
This is problematic for the following reasons:

1. it only works if `Form::handleRequest()` is called BEFORE the form is assembled. Any call to `Form::ensureAssembled()` before `Form::handleRequest()` will leave the value empty,
2. all uploaded files will be set to all file inputs, and
3. it does not work with nested form elements.
 
Read about the whole thing [here](https://www.php-fig.org/psr/psr-7/#16-uploaded-files).

I suggest doing the following in `Form::handleRequest()` before populating the `$params` to mitigate any issues mentioned above:

`$params = array_merge_recursive($params, $request->getUploadedFiles());`

2022-10-21 09:26 UTC, lippserd commented on src/FormElement/FileElement.php
> +    public function setValue($value)
`setValue()` is required for `populate()`. Do the following instead:

```php
    public function getValueAttribute()
    {
        // Value attributes of file inputs are set only client-side.
        return null;
    }
```

2022-10-21 09:26 UTC, lippserd commented on src/FormElement/FileElement.php
> +        $file = $this->value[$this->getName()];
Consider the changes requested in `onRegistered()`.

2022-10-21 09:26 UTC, lippserd commented on src/FormElement/FileElement.php
> +        return $this->hasValue() ? $this->value[$this->getName()] : null;
Consider the changes requested in `onRegistered()`.

2022-10-21 09:26 UTC, lippserd commented on tests/FormElement/FileElementTest.php
> +        $file = new FileElement('elname');
Use `test_file` for the element name.

2022-10-21 09:26 UTC, lippserd commented on tests/FormElement/FileElementTest.php
> +    public function testFileElement()
Rename to `testRendering()`.

2022-10-21 09:26 UTC, lippserd commented on tests/FormElement/FileElementTest.php
> +    public function testAcceptAttribute()
You can remove this. This will not test anything special from the file input.

2022-10-21 09:26 UTC, lippserd commented on tests/FormElement/FileElementTest.php
> +        $this->assertHtml('<input name="elname" type="file"/>', $file);
Already covered in `testRendering()`.

2022-10-21 09:26 UTC, lippserd commented on tests/FormElement/FileElementTest.php
> +    public function testSetValueDoesNotEffectAnything()
Rename to `testValueAttributeIsNotRendered()`

2022-10-21 09:26 UTC, lippserd commented on tests/FormElement/FileElementTest.php
> +class FileElementTest extends TestCase
Add the following test first:

```
    public function testElementLoading(): void
    {
        $form = (new Form())
            ->addElement('file', 'test_file');

        $this->assertInstanceOf(FileElement::class, $form->getElement('test_file'));
    }
}

2022-10-21 09:26 UTC, lippserd commented on tests/FormElement/FileElementTest.php
> +    public function testMultipleAttribute()
Rename to `testMutipleAttributeAlsoChangesNameAttribute()` and assert that `getName()` still returns the original name.

2022-11-14 13:23 UTC, nilmerg requested changes
While looking at the `testAcceptAttribute` test I wonder if it makes sense to automatically add the `FileValidator`. Should be considered, IMHO.

2022-11-14 13:23 UTC, nilmerg commented on src/FormElement/FileElement.php
> +    public function hasValue()
Here I wonder what happens if `$value` is null? Can it be null?

2022-11-14 13:23 UTC, nilmerg commented on tests/FormElement/FileElementTest.php
> +    public function testAcceptAttribute()
What purpose has this test? The `accept` attribute is not specifically processed by the element, so it's only subject to correct rendering. Though, for this, array syntax is missing. What about `true` and `false`? This is of course non-sense to assert here, it's a `FileElementTest` after all, not an `AttributeTest`. (Guess what, there's already such a test ;) )

Please remove this.

2022-11-17 11:27 UTC, sukhwinder33445 commented on src/FormElement/FileElement.php
> +    public function hasValue()
The `ServerRequest::normalizeFiles($_FILES)` call ensures that `ServerRequest::getUploadedFiles()` always returns `UploadedFileInterface|UploadedFileInterface[]`.

2022-11-18 14:26 UTC, nilmerg commented on src/FormElement/FileElement.php
> +    public function hasValue()
Okay, and what if no-one called `setValue()`?

2022-11-18 15:16 UTC, sukhwinder33445 commented on src/FormElement/FileElement.php
> +    public function hasValue()
This can only happen if `Form::populate()` cannot find the element. Can this be the case at all?

2022-11-18 15:27 UTC, nilmerg commented on src/FormElement/FileElement.php
> +    public function hasValue()
You're talking about a chronological situation here. The fact that the value can technically be null should already be enough.

2022-11-18 15:30 UTC, sukhwinder33445 commented on src/FormElement/FileElement.php
> +    public function hasValue()
Oh, got it. Thanks :)

2023-01-24 13:21 UTC, merged