Add `RadioElement`
Icinga/ipl-html pull request #68
Opened 2022-08-15 09:49 UTC by sukhwinder33445

2022-10-17 14:47 UTC, lippserd requested changes
In addition to the requested changes please

* use heredoc for the expected HTML and
* replace validation with something like an `InArray` validator provided in `addDefaultValidators()`.

2022-10-17 14:47 UTC, lippserd commented on src/FormElement/RadioElement.php
> +            $this->optionContent[$label] = $input;
Don't index by label but value. That way you can just use `isset()` in other code places. Use label of the input element for the label 😉.

2022-10-17 14:47 UTC, lippserd commented on src/FormElement/RadioElement.php
> +        return $this->renderContent();
Please justify this hack.

2022-10-21 15:22 UTC, sukhwinder33445 commented on src/FormElement/RadioElement.php
> +        $this->setName($name);
The `setOptions` setter callback requires $name before the parent constructor is even called.

2022-10-21 15:27 UTC, sukhwinder33445 commented on src/FormElement/RadioElement.php
> +            'disabled',
Since each radio has its own value, label and disable attribute, should `disabled => true` disable all? 🤔

2022-10-25 12:28 UTC, sukhwinder33445 commented on src/FormElement/RadioElement.php
> +        $this->setName($name);
Fixed. The parent constructor should call `setName()` before attributes are added.

2022-10-25 13:35 UTC, sukhwinder33445 commented on src/FormElement/RadioElement.php
> +        return $this->renderContent();
`Parent::renderUnwrapped()` requires `$tag` and the content should be empty. However, since we are creating each button in a label, the call to parent cannot work here and must be overridden.

2022-10-25 14:09 UTC, sukhwinder33445 commented
> * replace validation with something like an `InArray` validator provided in `addDefaultValidators()`.

This will not help much, since we also need to check for the `disabled` attribute. And all this should be done before parent::validate() is called. 🤔

2022-10-25 14:11 UTC, lippserd commented on src/FormElement/RadioElement.php
> +            'disabled',
> [...], should `disabled => true` disable all?

Yes.

2022-10-25 14:11 UTC, lippserd commented on src/FormElement/RadioElement.php
> +        return $this->renderContent();
As comment in the code please 😉.

2022-10-25 14:13 UTC, lippserd commented
> > * replace validation with something like an `InArray` validator provided in `addDefaultValidators()`.
> 
> This will not help much, since we also need to check for the `disabled` attribute. And all this should be done before parent::validate() is called. 🤔

The value should be validated against a list of possible values. Possible values are all options that are not disabled.

2022-10-26 07:09 UTC, lippserd commented
Please don't resolve conversations just for fun. I don't see anything resolved in the code.

2022-10-26 09:45 UTC, sukhwinder33445 commented on src/FormElement/RadioElement.php
> +        // ZF1 compatibility:
Removed.

2022-10-28 10:03 UTC, lippserd submitted a review, later dismissed
It should be `InArrayValidator` and not `InArray`, right?

I think it is best to have an option to defer which values to validate against in the `InArrayValidator`, by passing a callback to retrieve the possible values.

2022-10-28 10:05 UTC, lippserd commented
> It should be `InArrayValidator` and not `InArray`, right?
> 
> I think it is best to have an option to defer which values to validate against in the `InArrayValidator`, by passing a callback to retrieve the possible values.

Maybe `DeferredInArrayValidator`.

2022-10-28 14:09 UTC, TAINCER commented
This currently doesn't support adding custom `class` Attribute values to the Elements. Thus use cases where rendering different content based on the selection is not possible because it would need the class `autosubmit` attached to each Radio Input.

Would this be something to include?

2022-11-21 10:31 UTC, yhabteab commented
The element attributes also depend on the order in which they are added. E.g.:

This doesn't preselect the `each` option as the options are rendered after `setValue()`, I guess!
```php
$runsEach = $this->createElement('radio', 'runsOn', [
      'required' => true,
      'value'    => $this->getPopulatedValue('runsOn', 'each'),
      'options'  => ['each' => t('Each')],
]);
```

But this does preselect the option:

```php
$runsEach = $this->createElement('radio', 'runsOn', [
      'required' => true,
      'options'  => ['each' => t('Each')],
      'value'    => $this->getPopulatedValue('runsOn', 'each'),
]);
```

2022-11-23 12:20 UTC, nilmerg commented on src/FormElement/RadioElement.php
> +        return $this->renderContent();
Please use `HtmlDocument::renderUnwrapped()`. The implementation of `renderContent` may change.

2022-11-23 12:24 UTC, nilmerg commented on src/FormElement/RadioElement.php
> +                ->setAttributes(clone $this->getAttributes());
I'm not sure this is expected by the caller. Not every attribute is applicable to all options at the same time. Just think of the `id` attribute.

Important attributes can be adjusted by interacting with the options directly. (required, disabled, etc.) For what else should this be necessary?

Also, cloning attributes doesn't work correctly currently.

2022-11-23 12:26 UTC, nilmerg commented on src/FormElement/RadioElement.php
> +                        // But the attribute callback accepts limited return types.
It cannot return arrays. That's the only reason so please mention it.

2022-11-23 12:28 UTC, nilmerg commented on src/FormElement/RadioElement.php
> +            $labelElm = new HtmlElement(
Please don't use abbreviations in variable names. `$label` or `$labelElement`.

2022-11-23 12:29 UTC, nilmerg commented on src/FormElement/RadioElement.php
> +                HtmlString::create($option->getLabel())
`Text::create()` please. `HtmlString::create()` does not escape.

2022-11-23 12:32 UTC, nilmerg commented on src/FormElement/RadioOption.php
> +class RadioOption
Setters before getters please. Your arrangement currently isn't consistent as well.

2022-11-23 12:35 UTC, nilmerg commented on tests/FormElement/RadioElementTest.php
> +       $this->markTestSkipped('Requires https://github.com/Icinga/ipl-validator/pull/8');
Don't forget to remove this.

2022-11-23 12:35 UTC, nilmerg commented on tests/FormElement/RadioElementTest.php
> +        $this->markTestSkipped('Requires https://github.com/Icinga/ipl-validator/pull/8');
Don't forget to remove this.

2022-11-25 09:49 UTC, nilmerg requested changes
Since this has multiple values as well, please add a test like mentioned [here](https://github.com/Icinga/ipl-html/pull/88#discussion_r1032140457)

2022-11-25 09:49 UTC, nilmerg commented on src/FormElement/RadioElement.php
> +        foreach ($this->options as $option) {
Ah, just saw your wip commit. Yes, I don't think a setter for value is required. There's `setOptions` to change options.

2022-11-28 11:52 UTC, sukhwinder33445 commented on src/FormElement/RadioElement.php
> +                ->merge(new Attributes(['class' => $option->getlabelCssClass()]));
I had this before. But add does not support `$value` instance of `Attribute`.

2022-11-28 12:29 UTC, nilmerg commented on src/FormElement/RadioElement.php
> +                ->merge(new Attributes(['class' => $option->getlabelCssClass()]));
I see. But then I'd question why should this be possible:

`$form->getElement('radio')->getOption('foo')->setLabelCssClass(new Attribute('required', true))`

2022-11-28 15:48 UTC, nilmerg commented on src/FormElement/RadioElement.php
> +                ->add('class', $option->getlabelCssClass());
There's still this typo.

2022-11-28 15:48 UTC, nilmerg commented on src/FormElement/RadioOption.php
> +     * @param string|array|Attribute $labelCssClass
The types aren't in line with the getter.

2022-11-28 15:48 UTC, nilmerg commented on src/FormElement/RadioElement.php
> +                ->setDisabled(in_array($value, $this->disabledOptions, true));
I'm not sure `in_array` is suitable here. Remember, `''` and `null` should be equally handled.

2022-11-29 08:21 UTC, nilmerg requested changes
Missing tests:

* `testSetOptionsResetsOptions()`
* `testOrderOfOptionsAndDisabledOptionsDoesNotMatter()`
* `testGetOptionReturnsPreviouslySetOption()`
* ```php
    public function testNullAndTheEmptyStringAreAlsoEquallyHandledWhileDisablingOptions()
    {
        $radio = new RadioElement('radio');
        $radio->setOptions([null => 'Foo', 'bar' => 'Bar']);
        $radio->setDisabledOptions([null]);

        $this->assertTrue($radio->getOption(null)->isDisabled());

        $radio = new RadioElement('radio');
        $radio->setOptions(['' => 'Foo', 'bar' => 'Bar']);
        $radio->setDisabledOptions(['']);

        $this->assertTrue($radio->getOption('')->isDisabled());

        $radio = new RadioElement('radio');
        $radio->setOptions([null => 'Foo', 'bar' => 'Bar']);
        $radio->setDisabledOptions(['']);

        $this->assertTrue($radio->getOption(null)->isDisabled());
        $radio = new RadioElement('radio');
        $radio->setOptions(['' => 'Foo', 'bar' => 'Bar']);
        $radio->setDisabledOptions([null]);

        $this->assertTrue($radio->getOption('')->isDisabled());
    }
  ```
* ```php

    public function testGetOptionGetValueAndElementGetValueHandleNullAndTheEmptyStringEqually()
    {
        $radio = new RadioElement('radio');
        $radio->setOptions(['' => 'Foo']);
        $radio->setValue('');

        $this->assertNull($radio->getValue());
        $this->assertNull($radio->getOption('')->getValue());

        $radio = new RadioElement('radio');
        $radio->setOptions([null => 'Foo']);

        $this->assertNull($radio->getValue());
        $this->assertNull($radio->getOption(null)->getValue());
    }
  ```

2022-11-29 08:21 UTC, nilmerg commented on src/FormElement/RadioElement.php
> +                        && in_array(null, $this->disabledOptions, ! is_int($value)))
`$value` can't be `null`, as I showed you yesterday on the php-cli

2022-11-29 08:21 UTC, nilmerg commented on src/FormElement/RadioElement.php
> +        }
What's this? Tests succeed without it.

2022-11-29 08:21 UTC, nilmerg commented on src/FormElement/RadioElement.php
> +                    || (($value === '' || $value === null) && in_array(null, $disabledOptions, ! is_int($value)))
Same here, `$value` can't be `null`

2022-11-29 08:21 UTC, nilmerg commented on src/FormElement/RadioElement.php
> +                        return $this->getValue() === ($option->getValue() === '' ? null : $option->getValue());
`getOption` shouldn't have the empty string as value, the element doesn't as well after all.

2022-11-29 12:57 UTC, nilmerg requested changes

2022-11-29 12:57 UTC, nilmerg commented on src/FormElement/RadioElement.php
> +                    || ($value === '' && in_array(null, $disabledOptions))
Again, must be a strict comparison.

2022-11-29 12:57 UTC, nilmerg commented on src/FormElement/RadioOption.php
> +     * @return int|string
and... `null`.

2022-11-29 12:57 UTC, nilmerg commented on tests/FormElement/RadioElementTest.php
> +        $radio->getOption('foo');
I don't think the test continues running after this.

2022-11-29 13:34 UTC, sukhwinder33445 commented on tests/FormElement/RadioElementTest.php
> +        $radio->getOption('foo');
Yes, you are right. Moved it to the end of the test.

2022-11-30 08:04 UTC, nilmerg requested changes

2022-11-30 08:04 UTC, nilmerg commented on src/FormElement/RadioOption.php
> +    public function addLabelCssClass($labelCssClass): self
Rename this to `setLabelCssClass` please. The passed value should replace the default.

Anyone who still wants the default class, can do this: `$option->setLabelCssClass([RadioOption::LABEL_CLASS, 'new'])`

We don't provide a default style for `radio-label`, so there's nothing one could want to *keep*. And my suggestion recently for Yonas' problem would have the default made worse, because he would need to revert most of the CSS rules defined for the default class in order to hide the option. Even worse it could lead to this: `.radio-label:not(.hidden)`

So, being able to remove the default should be possible. Keeping the default also, which is the case by having the constant public.

2022-11-30 08:51 UTC, nilmerg commented on src/FormElement/RadioOption.php
> +     *  @return $this
~~Add~~Set

The `@return` has a superfluous space at the beginning.

2022-11-30 08:52 UTC, nilmerg commented on src/FormElement/RadioOption.php
> +    protected $labelCssClass = self::LABEL_CLASS;
Maybe use `static` instead. To be able to indeed subclass this and just override the constant.

2022-11-30 08:53 UTC, nilmerg commented on src/FormElement/RadioElement.php
> +                (new Attributes(['class' => $option->getLabelCssClass()])),
You don't need the parentheses around this.

2022-11-30 09:09 UTC, sukhwinder33445 commented on src/FormElement/RadioOption.php
> +    protected $labelCssClass = self::LABEL_CLASS;
It does not work. I get the hint mesaage `'static::' is not allowed in compile time constants`.

2022-11-30 11:15 UTC, nilmerg approved these changes

2022-12-06 07:50 UTC, yhabteab commented
Please add an option to render the input fields without wrapping them into the `radio-label`.

2022-12-06 08:46 UTC, sukhwinder33445 commented
> Please add an option to render the input fields without wrapping them into the `radio-label`.

Can you explain the use case please?

2022-12-06 09:00 UTC, yhabteab commented
I have a very special use case though that would stretch the scope to explain here but in short, I don't want the inputs to be wrapped in a label that I can neither access it with `getWrapper()` nor override it.

2022-12-14 09:18 UTC, merged