SelectOption: Add method `getLabel()` and change method `setLabel()`
Icinga/ipl-html pull request #70
Opened 2022-08-24 13:31 UTC by sukhwinder33445

2022-09-02 06:41 UTC, nilmerg commented
Please rebase here, there's a new test covering this change.

2022-09-02 12:00 UTC, lippserd reviewed
What is the purpose of this PR, i.e. why do you have to change the label after construction? Also, there's `setContent()` and `getContent()` which could just be used on the element.

2022-09-02 14:27 UTC, sukhwinder33445 commented
I noticed that label can be null in the constructor. It makes no sense to have an option without label. Maybe this should be fixed in a separate PR.

2022-09-02 14:27 UTC, lippserd commented
> What is the purpose of this PR, i.e. why do you have to change the label after construction? Also, there's `setContent()` and `getContent()` which could just be used on the element.

So you have updated the description. I suppose now it's just a matter of `getLabel()`. What do you want do with the label?

2022-09-02 14:31 UTC, lippserd commented
> I noticed that label can be null in the constructor. It makes no sense to have an option without label. Maybe this should be fixed in a separate PR.

We'll talk about that later. option can be used in several places and here and there it applies to have no value. For a select option, of course, this makes no sense. However, value could be empty, which then defaults to the content. I will create an issue for all this later. First, I want to understand what you want to do with the label.

2022-09-02 14:31 UTC, lippserd commented
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/option

2022-10-17 14:47 UTC, lippserd commented
@sukhwinder33445 This can be closed, right?

2022-10-21 14:28 UTC, lippserd requested changes
In addition to the requested changes, `setLabel()` must NOT be removed, see [here for a usage example](https://github.com/Icinga/icingaweb2-module-vspheredb/blob/master/library/Vspheredb/Web/Form/InfluxDbConnectionForm.php#L178).

 I would like to see the following tests:

* `testRendering`
* `testRenderingAfterSetLabel`
* `testGetLabel`
* `testGetLabelAfterSetLabel`

2022-10-28 11:57 UTC, nilmerg requested changes

2022-10-28 11:57 UTC, nilmerg commented on src/FormElement/SelectOption.php
> +     * @param string
`@param` requires also the name of the param

2022-11-07 08:29 UTC, nilmerg approved these changes

2022-11-07 10:51 UTC, lippserd requested changes

2022-11-07 10:51 UTC, lippserd commented on src/FormElement/SelectOption.php
> +    /** @var string Label of the option */
`string|null`

2022-11-07 10:51 UTC, lippserd commented on src/FormElement/SelectOption.php
>      public function setLabel($label)
`string $label` or `string $label = null` if we want to support resetting the label.

2022-11-07 10:51 UTC, lippserd commented on src/FormElement/SelectOption.php
>      public function setLabel($label)
Add return type.

2022-11-09 11:44 UTC, nilmerg commented
As we're changing this so fundamentally, may I ask what the purpose of a `SelectOption` without a value is? Once constructed, it's not possible to change it, so if not passed to the constructor, the value is permanently not set.
I'd also question that the label may not be set. What's the purpose of a `SelectOption` without a label?

2022-11-09 11:53 UTC, lippserd commented
> As we're changing this so fundamentally, may I ask what the purpose of a `SelectOption` without a value is? Once constructed, it's not possible to change it, so if not passed to the constructor, the value is permanently not set. I'd also question that the label may not be set. What's the purpose of a `SelectOption` without a label?

`null` is already used as value: https://github.com/Icinga/icingaweb2-module-vspheredb/blob/master/library/Vspheredb/Web/Form/InfluxDbConnectionForm.php#L60

Not having a label is questionable though.

2022-11-09 12:07 UTC, nilmerg commented on src/FormElement/SelectOption.php
> +    public function __construct(string $value = null, string $label = null)
Then I'd recommend this: (and the consequences for the other parts that follow)

```suggestion
    public function __construct(?string $value, string $label)
```

2022-11-30 08:40 UTC, nilmerg requested changes

2022-11-30 08:40 UTC, nilmerg commented on src/FormElement/SelectOption.php
> +    /** @var string|null Value of the option */
Please use `?string` here as well.

2022-11-30 08:40 UTC, nilmerg commented on src/FormElement/SelectOption.php
>       * @param string|null $value
Please use `?string`

2022-11-30 08:40 UTC, nilmerg commented on src/FormElement/SelectOption.php
> +     * Get the label of the option
The label?

2022-11-30 09:08 UTC, nilmerg approved these changes

2022-11-30 13:12 UTC, merged