Form: Only validate elements that have a value
Icinga/ipl-html pull request #86
Opened 2022-10-31 11:26 UTC by sukhwinder33445

fixes #85

2022-11-09 08:36 UTC, lippserd requested changes

2022-11-09 08:36 UTC, lippserd commented on src/Form.php
> +            } elseif (! $element->hasValue()) {
Instead of this `if ... elseif ...` construct with duplicate code (`$element->hasValue()` and `continue`) twice I suggest the following:

```
-            if ($element->isRequired() && ! $element->hasValue()) {
-                $element->addMessage('This field is required');
-                $valid = false;
+            if (! $element->hasValue()) {
+                if ($element->isRequired()) {
+                    $element->addMessage('This field is required');
+                    $valid = false;
+                }
+
                 continue;
             }
+
             if (! $element->isValid()) {
                 $valid = false;
             }
```

2022-11-09 09:06 UTC, nilmerg commented
I'd like to refer here to Zend Form's `allowEmpty` flag. It's default `true` there and has the same effect as this change. Though, unlike here, it's adjustable. Set to `false`, empty values are still passed on to validators. We rely on this in Icinga DB Web for example. There the Redis configuration is only valid if both a TLS certificate and a key are defined. Both options can only be empty or set at the same time. This is validated with a callback validator and represents essentially a conditional `required` flag.

It may be possible to achieve the same by actually setting the `required` flag based on a condition. Though, by doing this it bypasses the validation mechanics and hence has some disadvantages. For one, you can't nicely provide a contextual error message. You also can't chain it with other validators. It's also chronologically wrong as it *validates* during assembly.

So, in my opinion this should also be adjustable.

2022-11-09 15:42 UTC, lippserd commented
`allowEmpty` sounds good to me but I would let it default to `false`.

2022-11-14 08:09 UTC, nilmerg commented
Could you please be more elaborate on why `false` as default?

2022-11-15 14:34 UTC, lippserd requested changes
Please add a new property `validateEmpty` to the validators which is set to `false` by default (+ getter/setter). The `CallbackValidator` should have this property set to `true`. The validation chain must be adjusted to take the new property into account.

2023-01-16 12:45 UTC, nilmerg commented
The linked issue is now resolved by the change in ipl-validator.

2023-01-16 12:45 UTC, closed without merging