Enhance select element
Icinga/ipl-html pull request #88
Opened 2022-11-08 11:04 UTC by sukhwinder33445

2022-11-08 14:37 UTC, lippserd requested changes
Since you are adjusting the entire class, please define the proper arguments and return types for all methods the class provides itself.

2022-11-08 14:37 UTC, lippserd commented on src/FormElement/SelectElement.php
> +    public function setValue($value)
Why are you doing this?

It can be easily bypassed:

```php
(new SelectElement())->setValue('oops')->setAttribute('multiple', true);
```

The getter should return an array if `multiple` is `true`. Introducing dependencies in setters is not a good idea.

2022-11-08 14:37 UTC, lippserd commented on src/FormElement/SelectElement.php
> +            return in_array($optionValue, (array)$this->getValue(), ! is_int($optionValue));
Space missing after `(array)`.

2022-11-08 14:37 UTC, lippserd commented on tests/FormElement/SelectElementTest.php
> +        $html = <<<HTML
Please use nowdoc instead of heredoc everywhere.

2022-11-08 14:37 UTC, lippserd commented on src/FormElement/SelectElement.php
> +     * @param $optionValue
Type missing.

2022-11-10 07:50 UTC, lippserd requested changes
1. Please document the trait.
2. Please test the trait.
3. Don't drop ZF1 compatibility [yet](https://github.com/search?q=org%3AIcinga+org%3Agipfl+user%3AThomas-Gelf+multioptions&type=Code). I haven't checked if any of this applies to IPL forms, but I wouldn't bother to check either. The separate PR was fine.
4. The whole logic for disabling options is questionable as it is not possible to control this via construct time attributes and option groups cannot be disabled or the entire element (which effectively means all options (and groups) are automatically disabled). And the funniest thing is, it's not used at all, see [here](https://github.com/search?q=org%3AIcinga+org%3Agipfl+user%3AThomas-Gelf+disableOption&type=Code), [here](https://github.com/search?q=org%3AIcinga+org%3Agipfl+user%3AThomas-Gelf+disableOptions&type=Code), [here](https://github.com/search?q=org%3AIcinga+org%3Agipfl+user%3AThomas-Gelf+makeOption&type=Code) and [here](https://github.com/search?q=org%3AIcinga+org%3Agipfl+user%3AThomas-Gelf+SelectOption&type=Code). So we have a semi-implemented feature that is not used at all and just presents complexity for further changes. I would remove the ability to disable options.
5. And while we're removing stuff anyway, please drop `deselect()`. Also [not used](https://github.com/search?l=PHP&q=org%3AIcinga+org%3Agipfl+user%3AThomas-Gelf+deselect&type=Code).

2022-11-11 14:39 UTC, lippserd requested changes

2022-11-11 14:39 UTC, lippserd commented on src/FormElement/SelectElement.php
> +                $this->valid = false;
Do not do that. For example, setting `required` after validation doesn't reset `valid` either. Overall I would say there are way too many places to watch out for. I would rather suggest not caching `valid` in general. We only call it once anyway. But that's not something this PR should address.

2022-11-18 13:02 UTC, lippserd requested changes

2022-11-24 14:34 UTC, nilmerg requested changes

2022-11-24 14:34 UTC, nilmerg commented on src/FormElement/SelectElement.php
> +                    if ($option->getAttributes()->get('disabled')->getValue() === true) {
Please relax this. Someone might set `1` or `'disabled'` instead of `true`.

2022-11-24 14:34 UTC, nilmerg commented on src/FormElement/SelectElement.php
> -    public function disableOption($value)
Please restore the possibility to disable options.

This test must pass:

```php
    /**
     * @depends testNullAndTheEmptyStringAreEquallyHandled
     */
    public function testDisablingOptionsIsWorking()
    {
        $form = new Form();
        $form->addElement('select', 'select', [
            'options' => ['' => 'Please choose', 'foo' => 'FOO', 'bar' => 'BAR'],
            'disableOptions' => [''],
            'required' => true,
            'value' => ''
        ]);

        $this->assertHtml(<<<'HTML'
<select name="select" required>
  <option value selected disabled>Please choose</option>
  <option value="foo">FOO</option>
  <option value="bar">BAR</option>
</select>
HTML
            ,
            $form->getElement('select')
        );
    }
```

2022-11-24 14:34 UTC, nilmerg commented on src/FormElement/SelectElement.php
> +        $this->valid = null;
This has been introduced based on my suggestion. It should ultimately let the test below pass. Though, for this the identification of selected options may also be adjusted alternatively.


```php

    public function testNullAndTheEmptyStringAreEquallyHandled()
    {
        $form = new Form();
        $form->addElement('select', 'select', [
            'options' => ['' => 'Please choose'],
            'value' => ''
        ]);
        $form->addElement('select', 'select2', [
            'options' => [null => 'Please choose'],
            'value' => null
        ]);

        $select = $form->getElement('select');
        $select2 = $form->getElement('select2');

        $this->assertInstanceOf(SelectOption::class, $select->getOption(''));
        $this->assertInstanceOf(SelectOption::class, $select2->getOption(null));
        $this->assertInstanceOf(SelectOption::class, $select->getOption(null));
        $this->assertInstanceOf(SelectOption::class, $select2->getOption(''));

        $this->assertTrue($select->isValid());
        $this->assertTrue($select2->isValid());

        $this->assertHtml(<<<'HTML'
<select name="select">
  <option value selected>Please choose</option>
</select>
HTML
            ,
            $select
        );
        $this->assertHtml(<<<'HTML'
<select name="select2">
  <option value selected>Please choose</option>
</select>
HTML
            ,
            $select2
        );
    }
```

2022-11-25 08:57 UTC, nilmerg commented on src/FormElement/SelectElement.php
> +        $this->valid = null;
I've updated the test slightly. I prefer the alternative solution now (option identification) to make this non-distinction only an implementation detail.

```php
    public function testNullAndTheEmptyStringAreEquallyHandled()
    {
        $form = new Form();
        $form->addElement('select', 'select', [
            'options' => ['' => 'Please choose'],
            'value' => ''
        ]);
        $form->addElement('select', 'select2', [
            'options' => [null => 'Please choose'],
            'value' => null
        ]);

        /** @var SelectElement $select */
        $select = $form->getElement('select');
        /** @var SelectElement $select2 */
        $select2 = $form->getElement('select2');

        $this->assertNull($select->getValue());
        $this->assertNull($select2->getValue());

        $this->assertInstanceOf(SelectOption::class, $select->getOption(''));
        $this->assertInstanceOf(SelectOption::class, $select2->getOption(null));
        $this->assertInstanceOf(SelectOption::class, $select->getOption(null));
        $this->assertInstanceOf(SelectOption::class, $select2->getOption(''));

        $this->assertTrue($select->isValid());
        $this->assertTrue($select2->isValid());

        $select->setValue(null);
        $this->assertTrue($select->isValid());
        $select2->setValue('');
        $this->assertTrue($select2->isValid());

        $this->assertHtml(<<<'HTML'
<select name="select">
  <option value selected>Please choose</option>
</select>
HTML
            ,
            $select
        );
        $this->assertHtml(<<<'HTML'
<select name="select2">
  <option value selected>Please choose</option>
</select>
HTML
            ,
            $select2
        );
    }
```

2022-11-28 12:21 UTC, nilmerg requested changes

2022-11-28 12:21 UTC, nilmerg commented on src/FormElement/SelectElement.php
> +            return in_array($optionValue, $this->getValue(), ! is_int($optionValue));
`setValue([''])` isn't transformed to `setValue([null])`, so:

`in_array(null, [''], true) === false`

2022-11-28 12:21 UTC, nilmerg commented on src/FormElement/SelectElement.php
> +    public function setDisabledOptions(array $disabledOptions): self
Documentation please.

2022-11-28 12:21 UTC, nilmerg commented on tests/FormElement/SelectElementTest.php
> +    public function testSetArrayAsValueWithMultipleAttributeSetTheOptions()
Please add a case for `setValue([null])` and `setValue([''])`

2022-11-29 08:48 UTC, nilmerg requested changes
Missing tests:

* `testSetOptionsResetsOptions()`
* `testOrderOfOptionsAndDisabledOptionsDoesNotMatter()`
* `testGetOptionReturnsPreviouslySetOption()`
* ```php
    public function testNullAndTheEmptyStringAreAlsoEquallyHandledWhileDisablingOptions()
    {
        $radio = new SelectElement('radio');
        $radio->setOptions([null => 'Foo', 'bar' => 'Bar']);
        $radio->setDisabledOptions([null]);

        $this->assertTrue($radio->getOption(null)->getAttributes()->get('disabled')->getValue());

        $radio = new SelectElement('radio');
        $radio->setOptions(['' => 'Foo', 'bar' => 'Bar']);
        $radio->setDisabledOptions(['']);

        $this->assertTrue($radio->getOption('')->getAttributes()->get('disabled')->getValue());

        $radio = new SelectElement('radio');
        $radio->setOptions([null => 'Foo', 'bar' => 'Bar']);
        $radio->setDisabledOptions(['']);

        $this->assertTrue($radio->getOption(null)->getAttributes()->get('disabled')->getValue());
        $radio = new SelectElement('radio');
        $radio->setOptions(['' => 'Foo', 'bar' => 'Bar']);
        $radio->setDisabledOptions([null]);

        $this->assertTrue($radio->getOption('')->getAttributes()->get('disabled')->getValue());
    }
  ```
* ```php

    public function testGetOptionGetValueAndElementGetValueHandleNullAndTheEmptyStringEqually()
    {
        $radio = new SelectElement('radio');
        $radio->setOptions(['' => 'Foo']);
        $radio->setValue('');

        $this->assertNull($radio->getValue());
        $this->assertNull($radio->getOption('')->getValue());

        $radio = new SelectElement('radio');
        $radio->setOptions([null => 'Foo']);

        $this->assertNull($radio->getValue());
        $this->assertNull($radio->getOption(null)->getValue());
    }
  ```

2022-11-29 08:48 UTC, nilmerg commented on src/FormElement/SelectElement.php
> +            return ($optionValue === null && array_filter($this->getValue()) === [])
Why `array_filter`?? This can only result in an empty array if `''` or `null` is *chosen*, exclusively. This check fails if another option is chosen.

2022-11-29 10:12 UTC, sukhwinder33445 commented on src/FormElement/SelectElement.php
> +            return ($optionValue === null && array_filter($this->getValue()) === [])
Because it should not be possible to select the option `null` and some other options at the same time. $select->setValue(['', 5, 4]);` should mark only `5` and `4` as selected. 
I prefer to disable the '', null as default since they cannot be accepted as a valid value anyway.

2022-11-30 08:50 UTC, nilmerg commented on src/FormElement/SelectElement.php
> +            return ($optionValue === null && array_filter($this->getValue()) === [])
Not possible? Only if disabled. If enabled, the option should of course be choosable. Either way, this decision is not this code's duty. This is the validator's duty. An text input also isn't empty if invalid after all.. (Btw. if disabled, the browser doesn't let the user choose the option anyway)

2022-11-30 09:17 UTC, sukhwinder33445 commented on src/FormElement/SelectElement.php
> +            return ($optionValue === null && array_filter($this->getValue()) === [])
Yes, got it. I have already added the changes after my comment.

2022-11-30 11:16 UTC, nilmerg commented on src/FormElement/SelectElement.php
> +                    || ($optionValue === null && in_array('', $disabledOptions))
strict pls

2022-12-06 12:13 UTC, nilmerg approved these changes

2022-12-06 14:11 UTC, nilmerg requested changes

2022-12-06 14:11 UTC, nilmerg commented on src/FormElement/SelectElement.php
> +            throw new InvalidArgumentException(sprintf('There is no such option "%s"', $value));
This must not throw. It breaks compatibility way too hard and can't be worked around. Return null again if the option is unknown.

2022-12-21 15:59 UTC, sukhwinder33445 commented
@cla-bot check

2023-01-10 08:38 UTC, merged