Move form validation utils to `FormElements`
Icinga/ipl-html pull request #94
Opened 2022-11-24 13:31 UTC by yhabteab

2022-11-24 14:47 UTC, nilmerg requested changes

2022-11-24 14:47 UTC, nilmerg commented on src/FormElement/FormElements.php
> +    public function validatePartial(): self
This must also call `ensureAssembled`

2022-11-24 14:47 UTC, nilmerg commented on src/FormElement/FormElements.php
> +    public function validatePartial(): self
Also: remove the return type declaration. I don't want a breaking change just due to this.

2022-11-24 15:03 UTC, nilmerg requested changes

2022-11-24 15:03 UTC, nilmerg commented on src/FormElement/FormElements.php
> +                $element->addMessage('This field is required');
While you're at it, please translate this.

2022-11-24 15:03 UTC, nilmerg commented on src/FormElement/FormElements.php
> +     * {@see validate()} is called automatically if the form has not been validated before.
Use `self::validate()`, otherwise one might think this is a function.

2022-11-24 15:03 UTC, nilmerg commented on src/FormElement/FormElements.php
> +     * Get whether this form is valid
Technically, this now returns whether all elements are valid or not.

2022-11-24 15:17 UTC, nilmerg commented on src/FormElement/FormElements.php
> +    use Translation;
Could you please check what happens if child classes also use this trait?

2022-11-24 15:26 UTC, yhabteab commented on src/FormElement/FormElements.php
> +    use Translation;
No errors, if that's what you're getting after.

2022-11-24 15:32 UTC, yhabteab commented on src/FormElement/FormElements.php
> +    use Translation;
Ah, wait! If you use both traits, i.e. `FormElements` and `Translation` in the same class, then there is a method collision, but if you use the translation trait in a child class of a class that uses `FormElements`, then it's fine.

2022-11-25 08:04 UTC, nilmerg commented on src/FormElement/FormElements.php
> +    use Translation;
> then there is a method collision

That's fine. Thanks.

2022-11-25 08:05 UTC, nilmerg approved these changes

2022-11-29 10:53 UTC, merged